console.log("My first console project");
var first_name = "Ismail";
console.log(first_name);
var last_name = "Hassan";
console.log(last_name);
var full_name = first_name.concat(last_name);
console.log(full_name);
var a = 10;
var b = 5;
var add = a+b;
console.log(add);
var mul = a*b;
console.log(mul);
var sub = a-b;
console.log(sub);
var div = a/b;
console.log(div);